#!/usr/bin/env bash

WINEPREFIX=~/Games/world-of-warcraft ~/.local/share/lutris/runners/wine/pba-firerat-3.11-x86_64/bin/wine ~/Games/world-of-warcraft/drive_c/Program\ Files\ \(x86\)/TradeSkillMaster\ Application/app/TSMApplication.exe
