#!/usr/bin/env bash

#URL="https://source.unsplash.com/featured/3840x2160"
URL="https://source.unsplash.com/3840x2160?wallpaper"
# celestial collection
#URL="https://source.unsplash.com/collection/543026/3840x2160"
# storms
#URL="https://source.unsplash.com/collection/1089430/3840x2160"
# inspiring views
#URL="https://source.unsplash.com/collection/932809/3840x2160"


cd ~/tmp || exit
wget -q $URL -O wallpaper.jpg

feh --bg-fill wallpaper.jpg
wal -i wallpaper.jpg -g